_wandb:
    value:
        cli_version: 0.19.5
        m: []
        python_version: 3.8.10
        t:
            "1":
                - 12
                - 45
                - 55
            "2":
                - 12
                - 45
                - 55
            "3":
                - 23
                - 55
            "4": 3.8.10
            "5": 0.19.5
            "8":
                - 5
            "12": 0.19.5
            "13": linux-x86_64
